const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const ROOT=__dirname,DB=path.join(ROOT,'data','db.json'),PORT=process.env.PORT||3000;
const seed={users:[],tasks:[{id:'t1',title:'অ্যাপ / ওয়েব ভিজিট',description:'২ মিনিট • নির্দেশনা অনুসরণ করুন',reward:25,icon:'📱',active:true},{id:'t2',title:'ভিডিও রিভিউ',description:'৫ মিনিট • প্রমাণ প্রয়োজন',reward:40,icon:'▶️',active:true},{id:'t3',title:'ছোট সার্ভে',description:'৩ মিনিট • একবার/দিন',reward:55,icon:'📝',active:true}],transactions:[],notifications:[],sessions:[]};
function load(){if(!fs.existsSync(path.dirname(DB)))fs.mkdirSync(path.dirname(DB),{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed,null,2));return JSON.parse(fs.readFileSync(DB,'utf8'))}let db=load();
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}function rid(p){return p+'_'+crypto.randomBytes(8).toString('hex')}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return new Promise((r,j)=>crypto.scrypt(p,s,64,(e,d)=>e?j(e):r(s+':'+d.toString('hex'))))}async function verify(p,h){const [s,d]=h.split(':');const x=await hash(p,s);return crypto.timingSafeEqual(Buffer.from(x.split(':')[1],'hex'),Buffer.from(d,'hex'))}
function cookies(req){const o={};(req.headers.cookie||'').split(';').forEach(v=>{const [k,...a]=v.trim().split('=');if(k)o[k]=a.join('=')});return o}function user(req){const sid=cookies(req).mzsid,s=db.sessions.find(x=>x.id===sid&&x.expires>Date.now());return s?db.users.find(x=>x.id===s.userId):null}
function out(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(data))}function pub(u){return u&&{id:u.id,uid:u.uid,name:u.name,phone:u.phone,balance:u.balance,pending:u.pending,refCode:u.refCode,role:u.role,createdAt:u.createdAt}}
async function body(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function auth(req,res,admin=false){const u=user(req);if(!u)return out(res,401,{error:'লগইন করুন।'});if(admin&&u.role!=='admin')return out(res,403,{error:'Admin access required'});return u}
function tx(u,type,amount,status,extra={}){const t={id:rid('tx'),userId:u.id,type,amount:Number(amount),status,createdAt:new Date().toISOString(),...extra};db.transactions.push(t);return t}
async function main(req,res){const p=url.parse(req.url,true).pathname;
 if(req.method==='GET'&&p==='/api/me'){return out(res,200,{user:pub(user(req))})}
 if(req.method==='POST'&&p==='/api/register'){const b=await body(req);if(!b.name||!/^[0-9]{11}$/.test(b.phone)||!b.password||b.password.length<6)return out(res,400,{error:'নাম, ১১ সংখ্যার মোবাইল ও কমপক্ষে ৬ অক্ষরের পাসওয়ার্ড দিন।'});if(db.users.some(x=>x.phone===b.phone))return out(res,409,{error:'এই মোবাইল নম্বর আগে থেকেই নিবন্ধিত।'});let uid;do{uid='MZ-'+Math.floor(100000+Math.random()*900000)}while(db.users.some(x=>x.uid===uid));let u={id:rid('usr'),uid,name:b.name.trim(),phone:b.phone,balance:0,pending:0,password:await hash(b.password),role:'user',refCode:'MZ'+crypto.randomBytes(4).toString('hex').toUpperCase(),createdAt:new Date().toISOString()};db.users.push(u);if(b.refCode){const ref=db.users.find(x=>x.refCode===String(b.refCode).trim()&&x.id!==u.id);if(ref){tx(ref,'referral_reward',25,'approved',{fromUserId:u.id});ref.balance+=25}}const sid=rid('sess');db.sessions.push({id:sid,userId:u.id,expires:Date.now()+7*86400000});db.notifications.push({id:rid('nt'),userId:u.id,title:'স্বাগতম!',message:'MAXEARN ZONE-এ আপনার অ্যাকাউন্ট তৈরি হয়েছে।',category:'account',unread:true,createdAt:new Date().toISOString()});save();return out(res,201,{user:pub(u)},{'Set-Cookie':`mzsid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`})}
 if(req.method==='POST'&&p==='/api/login'){const b=await body(req),u=db.users.find(x=>x.phone===b.phone);if(!u||!(await verify(b.password||'',u.password)))return out(res,401,{error:'মোবাইল বা পাসওয়ার্ড সঠিক নয়।'});const sid=rid('sess');db.sessions.push({id:sid,userId:u.id,expires:Date.now()+604800000});save();return out(res,200,{user:pub(u)},{'Set-Cookie':`mzsid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`})}
 if(req.method==='POST'&&p==='/api/logout'){const sid=cookies(req).mzsid;db.sessions=db.sessions.filter(x=>x.id!==sid);save();return out(res,200,{ok:true},{'Set-Cookie':'mzsid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(req.method==='GET'&&p==='/api/tasks'){return out(res,200,{tasks:db.tasks.filter(x=>x.active)})}
 if(req.method==='POST'&&/^\/api\/tasks\/[^/]+\/claim$/.test(p)){const u=auth(req,res);if(!u)return;const id=p.split('/')[3],t=db.tasks.find(x=>x.id===id&&x.active),day=new Date().toISOString().slice(0,10);if(!t)return out(res,404,{error:'টাস্ক পাওয়া যায়নি।'});if(db.transactions.some(x=>x.userId===u.id&&x.type==='task_reward'&&x.taskId===id&&x.date===day))return out(res,409,{error:'আজকের টাস্কটি ইতিমধ্যে সম্পন্ন হয়েছে।'});u.balance+=t.reward;tx(u,'task_reward',t.reward,'approved',{taskId:id,date:day});db.notifications.push({id:rid('nt'),userId:u.id,title:'Task Reward',message:`৳${t.reward} আপনার ব্যালেন্সে যোগ হয়েছে।`,category:'balance',unread:true,createdAt:new Date().toISOString()});save();return out(res,200,{user:pub(u),message:`৳${t.reward} Reward যোগ হয়েছে।`})}
 if(req.method==='GET'&&p==='/api/transactions'){const u=auth(req,res);if(!u)return;return out(res,200,{transactions:db.transactions.filter(x=>x.userId===u.id).slice(-100).reverse()})}
 if(req.method==='POST'&&p==='/api/deposit'){const u=auth(req,res);if(!u)return;const b=await body(req),amount=Number(b.amount);if(!['bKash','Nagad'].includes(b.method)||!Number.isFinite(amount)||amount<100||!/^01[0-9]{9}$/.test(b.account)||!b.reference)return out(res,400,{error:'মাধ্যম, পরিমাণ, অ্যাকাউন্ট ও Transaction ID দিন।'});tx(u,'deposit',amount,'pending',{method:b.method,account:b.account,reference:b.reference});db.notifications.push({id:rid('nt'),userId:u.id,title:'Deposit Request',message:'আপনার deposit যাচাইয়ের অপেক্ষায় আছে।',category:'balance',unread:true,createdAt:new Date().toISOString()});save();return out(res,201,{message:'Deposit request জমা হয়েছে। Admin যাচাই করার পর ব্যালেন্সে যোগ হবে।'})}
 if(req.method==='POST'&&p==='/api/withdraw'){const u=auth(req,res);if(!u)return;const b=await body(req),amount=Number(b.amount);if(!['bKash','Nagad'].includes(b.method)||!Number.isFinite(amount)||amount<100||amount>u.balance||!/^01[0-9]{9}$/.test(b.account))return out(res,400,{error:'ন্যূনতম ৳100, সঠিক মাধ্যম ও ১১ সংখ্যার অ্যাকাউন্ট দিন।'});u.balance-=amount;u.pending+=amount;tx(u,'withdraw',amount,'pending',{method:b.method,account:b.account});db.notifications.push({id:rid('nt'),userId:u.id,title:'Withdrawal Request',message:`৳${amount} withdrawal request জমা হয়েছে।`,category:'balance',unread:true,createdAt:new Date().toISOString()});save();return out(res,201,{user:pub(u),message:'Withdrawal request জমা হয়েছে।'})}
 if(req.method==='GET'&&p==='/api/rewards'){const u=auth(req,res);if(!u)return;return out(res,200,{rewards:db.transactions.filter(x=>x.userId===u.id&&['task_reward','referral_reward','bonus'].includes(x.type)).slice(-100).reverse()})}
 if(req.method==='GET'&&p==='/api/notifications'){const u=auth(req,res);if(!u)return;return out(res,200,{notifications:db.notifications.filter(x=>x.userId===u.id||!x.userId).slice(-50).reverse()})}
 if(req.method==='POST'&&p==='/api/notifications/read'){const u=auth(req,res);if(!u)return;db.notifications.filter(x=>x.userId===u.id).forEach(x=>x.unread=false);save();return out(res,200,{ok:true})}
 if(req.method==='PUT'&&p==='/api/profile'){const u=auth(req,res);if(!u)return;const b=await body(req);if(b.name)u.name=String(b.name).trim();save();return out(res,200,{user:pub(u)})}
 if(req.method==='POST'&&p==='/api/password'){const u=auth(req,res);if(!u)return;const b=await body(req);if(!b.current||!b.next||b.next.length<6||!(await verify(b.current,u.password)))return out(res,400,{error:'বর্তমান পাসওয়ার্ড সঠিক নয় অথবা নতুন পাসওয়ার্ড ছোট।'});u.password=await hash(b.next);save();return out(res,200,{message:'পাসওয়ার্ড পরিবর্তন হয়েছে।'})}
 if(req.method==='GET'&&p==='/api/admin/stats'){const u=auth(req,res,true);if(!u)return;return out(res,200,{stats:{members:db.users.filter(x=>x.role==='user').length,rewardPaid:db.transactions.filter(x=>['task_reward','referral_reward','bonus'].includes(x.type)&&x.status==='approved').reduce((a,x)=>a+x.amount,0),pendingDeposits:db.transactions.filter(x=>x.type==='deposit'&&x.status==='pending').length,pendingWithdrawals:db.transactions.filter(x=>x.type==='withdraw'&&x.status==='pending').length,activeTasks:db.tasks.filter(x=>x.active).length}})}
 if(req.method==='GET'&&p==='/api/admin/users'){const u=auth(req,res,true);if(!u)return;return out(res,200,{users:db.users.filter(x=>x.role==='user').map(pub)})}
 if(req.method==='GET'&&p==='/api/admin/requests'){const u=auth(req,res,true);if(!u)return;return out(res,200,{requests:db.transactions.filter(x=>['deposit','withdraw'].includes(x.type)).slice(-100).reverse()})}
 if(req.method==='POST'&&p==='/api/admin/tasks'){const u=auth(req,res,true);if(!u)return;const b=await body(req),reward=Number(b.reward);if(!b.title||!Number.isFinite(reward)||reward<=0)return out(res,400,{error:'Task title ও সঠিক reward দিন।'});const t={id:rid('task'),title:String(b.title),description:String(b.description||''),reward,icon:b.icon||'🎯',active:true};db.tasks.push(t);save();return out(res,201,{task:t})}
 if(req.method==='PATCH'&&/^\/api\/admin\/tasks\/[^/]+$/.test(p)){const u=auth(req,res,true);if(!u)return;const t=db.tasks.find(x=>x.id===p.split('/')[4]);if(!t)return out(res,404,{error:'Task not found'});const b=await body(req);if(typeof b.active==='boolean')t.active=b.active;if(b.title)t.title=String(b.title);if(b.reward!==undefined)t.reward=Number(b.reward);save();return out(res,200,{task:t})}
 if(req.method==='POST'&&/^\/api\/admin\/requests\/[^/]+\/approve$/.test(p)){const u=auth(req,res,true);if(!u)return;const t=db.transactions.find(x=>x.id===p.split('/')[4]);if(!t||t.status!=='pending')return out(res,404,{error:'Pending request not found'});const owner=db.users.find(x=>x.id===t.userId);if(!owner)return out(res,404,{error:'User not found'});t.status='approved';if(t.type==='deposit')owner.balance+=t.amount;if(t.type==='withdraw')owner.pending=Math.max(0,owner.pending-t.amount);db.notifications.push({id:rid('nt'),userId:owner.id,title:t.type==='deposit'?'Deposit Approved':'Withdrawal Approved',message:`৳${t.amount} request approved হয়েছে।`,category:'balance',unread:true,createdAt:new Date().toISOString()});save();return out(res,200,{ok:true})}
 if(req.method==='POST'&&p==='/api/admin/notify'){const u=auth(req,res,true);if(!u)return;const b=await body(req);if(!b.title||!b.message)return out(res,400,{error:'Title ও message দিন।'});db.notifications.push({id:rid('nt'),title:String(b.title),message:String(b.message),category:b.category||'promotion',unread:true,createdAt:new Date().toISOString()});save();return out(res,201,{ok:true})}
 if(req.method==='POST'&&p==='/api/admin/bootstrap'){if(db.users.some(x=>x.role==='admin'))return out(res,409,{error:'Admin already exists'});const b=await body(req);if(!b.phone||!b.password)return out(res,400,{error:'Admin phone/password দিন'});const u={id:rid('usr'),uid:'MZ-ADMIN',name:b.name||'Administrator',phone:b.phone,password:await hash(b.password),balance:0,pending:0,role:'admin',refCode:'ADMIN',createdAt:new Date().toISOString()};db.users.push(u);save();return out(res,201,{message:'Admin created'})}
 if(req.method==='GET'&&p==='/api/health')return out(res,200,{ok:true,name:'MAXEARN ZONE'});
 if(req.method==='GET'&&p==='/')return serve(res,path.join(ROOT,'index.html'));const f=path.normalize(path.join(ROOT,p));if(f.startsWith(ROOT)&&fs.existsSync(f)&&fs.statSync(f).isFile())return serve(res,f);res.writeHead(404);res.end('Not found')}
function serve(res,f){const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json'};res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}
http.createServer((q,s)=>main(q,s).catch(e=>{console.error(e);out(s,500,{error:'Server error'})})).listen(PORT,()=>console.log(`MAXEARN ZONE: http://localhost:${PORT}`));
